### ISSUE TITLE
GitHub code retrieval problem

### ISSUE THREAD

**Issue by mjaniec2013** [stevecondylios/rawr#1]
`rawr()` retrieved just a couple of lines (not necessarily from the beginning) from [https://github.com/mjaniec2013/ExecutionTime/blob/master/ExecutionTime.R](url)

Code used:
```R
library(rawr)

code <- rawr("https://github.com/mjaniec2013/ExecutionTime/blob/master/ExecutionTime.R")

cat(code)
```

**Comment by stevecondylios** [comment]
Thanks for raising. This occurred because `xml2::read_html()` doesn't know how to parse the `<` character (it thinks it's an html tag). 

This has been fixed in the `rawr` package here on github - it can be installed with `devtools::install_github("stevecondylios/rawr")` until that version makes its way on to CRAN.
